# Generated by Django 4.0.1 on 2022-01-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_profile_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='extra_id',
            field=models.CharField(db_index=True, default='0001', max_length=4, verbose_name='Идентификатор'),
            preserve_default=False,
        ),
    ]
