# Generated by Django 4.0.1 on 2022-01-26 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0008_profile_extra_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Содержание')),
                ('typeof', models.CharField(max_length=100, verbose_name='Тип уведомления')),
                ('is_viewed', models.BooleanField(default=False, verbose_name='Просмотрено')),
                ('is_visible', models.BooleanField(default=True)),
                ('from_user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outcome_notifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
