# Generated by Django 4.0.1 on 2022-01-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_deck'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='deck/%Y/%m/%d', verbose_name='Изображение'),
        ),
    ]
