# Generated by Django 4.0.1 on 2022-01-15 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_deck_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='deck',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('-created',)},
        ),
    ]
