# Generated by Django 4.0.1 on 2022-01-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_answer_options_alter_deck_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Ответ опубликован?'),
        ),
    ]
