# Generated by Django 4.0.1 on 2022-01-24 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0009_alter_deck_answers_alter_deck_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=False, verbose_name='Игра запущена?')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания игры')),
                ('deck', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='game.deck')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.IntegerField(default=0, verbose_name='Количество ответов всего')),
                ('wins', models.IntegerField(default=0, verbose_name='Количество побед')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='game.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(related_name='game', through='game.Membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL),
        ),
    ]
